### ISSUE TITLE
使用默认配置

### ISSUE THREAD

**Issue by iconFehu** [ApliNi/AutoUpdatePlugins#2]
请看这个配置文件
![image](https://github.com/ApliNi/AutoUpdatePlugins/assets/46149128/1b2caa0f-ac8e-4b56-9a5b-8aaea4598318)
我只去掉了注释，控制台出现更新失败的提示
![image](https://github.com/ApliNi/AutoUpdatePlugins/assets/46149128/17e79a35-3988-432f-91af-357e959b50ac)
请问如何解决此报错

**Comment by ApliNi** [comment]
这是网络的问题, 我也会经常遇到, 可以尝试在浏览器里打开这个 url, 看看能不能下载到文件. 或者给服务器挂梯子 (

**Comment by iconFehu** [comment]
直接在chrome浏览器中打开此链接目前是可以正常下载的

**Comment by ApliNi** [comment]
我依然认为这是网络问题, 我会在下一次更新中使用更稳定的 HTTP 客户端库来尝试改善网络连接. 感谢你提交这个错误

**Comment by ApliNi** [comment]
发布了新版本, 应该能解决这个问题

---

**Full Changelog**: https://github.com/ApliNi/AutoUpdatePlugins/compare/v2.4.3...v2.5.0

**更新内容**
- 使用更稳定的网络请求库优化稳定性
- 支持添加网络代理
- 支持运行在 Folia 服务器上

**配置改动**
- 移除 `disableCertificateVerification` 配置, 添加 `proxy` 配置
```yaml
# 设置网络代理
proxy:
  type: DIRECT # DIRECT | HTTP | SOCKS
  host: '127.0.0.1'
  port: 7890
```
